export const SALT_ROUNDS = 10;
export const POST_TITLE_MIN_LENGTH=20
export const POST_TITLE_MAX_LENGTH=50
export const POST_PHOTO_MAX_FILE_SIZE_MB=1
export const POST_ANNOUNCEMENT_MIN_LENGTH=50
export const POST_ANNOUNCEMENT_MAX_LENGTH=255
export const POST_TEXT_MIN_LENGTH=100
export const POST_TEXT_MAX_LENGTH=1024
export const POST_QUOTE_MIN_LENGTH=20
export const POST_QUOTE_MAX_LENGTH=300
export const POST_QUOTE_AUTHOR_MIN_LENGTH=3
export const POST_QUOTE_AUTHOR_MAX_LENGTH=50
export const POST_LINK_DESCRIPTION_MIN_LENGTH=1
export const POST_LINK_DESCRIPTION_MAX_LENGTH=300
export const POST_TAG_MIN_LENGTH=3
export const POST_TAG_MAX_LENGTH=10
export const POST_MAX_TAGS_ALLOWED=8

